apiVersion: batch/v1beta1
kind: CronJob
metadata: 
  name: enajusp-deletarbkp-legado
  namespace: enajusp-dsv
spec: 
  jobTemplate: 
    metadata: 
      creationTimestamp: ~
    spec: 
      template: 
        spec: 
          containers: 
            - 
              args: 
                - "rm -rf /bitnami/moodledata/moodledata/temp/backup/*"
              command: 
                - /bin/sh
                - "-c"
              image: alpine
              imagePullPolicy: IfNotPresent
              name: enajusp-deletar-backup
              volumeMounts: 
                - 
                  mountPath: /bitnami/moodledata
                  name: disk01
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          volumes: 
            - 
              name: disk01
              persistentVolumeClaim: 
                claimName: pvc-legadoeadsegen-moodle-dsv
  schedule: "0 7,11,15,19,23,3 * * *"
