# PV E PVC

apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-nfs-hml-ns-trt
    namespace: enajusp-prd
spec:
    storageClassName: ''
    capacity:
      storage: 100Gi
    accessModes:
    - ReadWriteMany
    nfs:
      server: 10.250.232.4
      path: /enajusp-moodle-dsv
    mountOptions:
    - rw
    - hard
    - rsize=1048576
    - wsize=1048576
    - sec=sys
    - vers=3
    - tcp

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-eadsegen-moodledata
  namespace: enajusp-dsv
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem  
  resources:
    requests:
      storage: 100Gi
  storageClassName: ''
