#EXEMPLO ABAIXO CRIA UM SECRETSTORE E UM EXTERNALSECRET QUE IRA CRIAR UM SECRET COM AS CHAVES DA HASHICORP
#NO EXEMPLO IRA CRIAR UM SEGREDO CHAMADO SAVI COM AS CHAVES DO AMBIENTE PRDSAVI

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: savi
  namespace: savi-prd
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kube-app-production-aks02
          role: k8s
      path: application
      server: https://vault.mj.gov.br
      version: v2

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: savi
  namespace: savi-prd
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: prd/savi
  refreshInterval: 2m
  secretStoreRef:
    kind: SecretStore
    name: savi
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: savi
